[project]
name = "glm-asr-stt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "customtkinter>=5.2.2",
    "pillow>=12.0.0",
    "silero-vad>=6.2.0",
]
